server:
  port: 8761
spring:
  application:
    name: server.online.shop
  cloud:
    config:
      import-check:
        enabled: false
eureka:
  username: user
  password: password
#  username: ${USERNAME:username}
#  password: ${PASSWORD:password}
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://host:docker:internal:8761/eureka/
#  instance:
#    hostname: localhost


