server:
  port: 8761
spring:
  application:
    name: server-online-shop
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
