server:
  port : 8903
spring:
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    config:
#      enabled: false
  application:
    name: order.microservice
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online.shop
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
