server:
  name: 8900
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  application:
    name: api.gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
