server:
  port: 8900
spring:
  application:
    name: api.gateway
  cloud:
    gateway:
      routes:
      - id: client.microservice
        uri: lb://client.microservice
        predicates:
        - Path=/client/**
      - id: product.microservice
        uri: lb://product.microservice
        predicates:
        - Path=/product/**
      - id: order.microservice
        uri: lb://order.microservice
        predicates:
        - Path=/order/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      client:
        provider:
          keycloack:
            issuer-uri: http://localhost:8181/realms/master
            token-uri: http://localhost:8181/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:8181/realms/master/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8181/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred-username
        registration:
          online-shop-gateway:
            provider: keycloak
            client-id: online-shop-api-gateway
            client-secret: CMdOsPVlQTYruL3n8SX4aZRfSnm0KTHZ
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/online-shop-microservices
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
