server:
  port: 8900
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  application:
    name: api.gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
