server:
  port : 8902
spring:
  cloud:
    config:
      enabled: false
  application:
    name: client.microservice
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online.shop
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/master/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
resilience4j.retry:
  instances:
    client:
      maxAttempts: 7
      waitDuration: 1s
      enableExponentialBackoff: true
